## Introduction to Python and Google Colab


### - Python

There are multiple ways to write code and perform your experiments.

__Option 1__: Stand-alone python scripts. Let your python file be "myfirstscript.py", then you can run it simply openning a terminal and running: 
        
    python myfirstscript.py
    
__Option 2__: Using iPython interactive shell. Here an environment is opened for you where you the variables of your script you want to execute are resident and you can interact with them. Initially, you open an iPython shell from a terminal:
    
    iPython
    
Then, let us say "myfirstscript.py" has a variable named $x$ you can examine your results, simply by running:

    run myfirstscript.py
    print(x)

__Option 3__: Using Jupyter Notebook. This is a browser based manner to interact with the _iPython_ shell. You have to start the Jupyter server by executing the following in a terminal and follow the instructions.. 
    
    jupyter notebook
    
### - Working on Google Colab
  Google Colab offers an environment for everyone who intends to try out his Machine Learning projects. 

__Option 1__: Type the following link within your browser:

    colab.research.google.com

Then, upload the desired jupyter notebook:

    lab0_warmup.ipynb

Ready to go!


## Numpy (https://numpy.org/)

The library to perform math operations.

In [2]:
# Import Numpy library
import numpy as np

#### Indexing

Python begins indexing at 0 (not 1), therefore the first row and first column is referenced by 0,0 not 1,1.

#### Slicing

Accessing elements of numpy matrices and arrays. 

Let: <br>
<p style="text-align: center">
$\mathbf{A} = \begin{bmatrix}0 & 1 \\ 2&3\end{bmatrix}$ 
</p>
Then,<br>

<p style="text-align: center">
    $\mathbf{A}[:,0]=\begin{bmatrix}0 \\ 2 \end{bmatrix} \rightarrow$ grabs the first <b>column</b> of matrix $\mathbf{A}$    
</p>
while <br>
<p style="text-align: center">
    $\mathbf{A}[0,:]=\begin{bmatrix}0 \\ 2 \end{bmatrix} \rightarrow$ grabs the first <b>row</b> of matrix $\mathbf{A}$    
</p>

In [8]:
# define matrix A
A = np.array([[0,1],[2,3]]) # or alternativelly A=np.arange(4).reshape((2,2))
print(A)

[[0 1]
 [2 3]]


In [9]:
# get dimensions of A
dim = A.shape
print(dim)

(2, 2)


In [18]:
# get the second element of second row
a = A[1,1]
print(a)

3


In [11]:
# get second row of A
C = A[1,:]
print(C)

[2 3]


In [13]:
# get first column of A
C = A[:,0]
print(C)

[0 2]


#### - Logical Checks to extract values from matrices/arrays

In [14]:
print(A)

[[0 1]
 [2 3]]


In [17]:
# Extract values from A that are bigger than 1 (>1)
C = A[A>1]
print(C)

[2 3]


#### - For loops
Create a $5x5$ matrix 

<p style="text-align:center">
    $\mathbf{A}=\begin{bmatrix}0 & 1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 & 9 \\ 10 & 11 & 12 & 13 & 14 \\ 15 & 16 & 17 & 18 & 19 \\ 20 & 21 & 22 & 23 & 24\end{bmatrix}$</p>
    
Now extract one row at a time and print it out:
<p style="text-align:center">
    $\mathbf{A}[0,:]=\begin{bmatrix}0 & 1 & 2 & 3 & 4 \end{bmatrix}$<br> $\vdots$<br>
    $\mathbf{A}[4,:]=\begin{bmatrix}20 & 21 & 22 & 23 & 24 \end{bmatrix}$
</p>


In [22]:
# Define Matrix A
A = np.arange(25).reshape((5,5))
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [31]:
# extract each row of A and print it out along with its index
row_counter = 0
for row in A:    
    print('A[',row_counter,',:]=',row)
    row_counter=row_counter + 1

print('-------------------')

# or alternatively
for row_counter2,row in enumerate(A):
    print('A[',row_counter2,',:]=',row)

A[ 0 ,:]= [0 1 2 3 4]
A[ 1 ,:]= [5 6 7 8 9]
A[ 2 ,:]= [10 11 12 13 14]
A[ 3 ,:]= [15 16 17 18 19]
A[ 4 ,:]= [20 21 22 23 24]
-------------------
A[ 0 ,:]= [0 1 2 3 4]
A[ 1 ,:]= [5 6 7 8 9]
A[ 2 ,:]= [10 11 12 13 14]
A[ 3 ,:]= [15 16 17 18 19]
A[ 4 ,:]= [20 21 22 23 24]


#### - If/then/else
The code below checks the value of x and categorizes it into one of three values. Like the for loop, each logical if check is ended with a colon, and any commands to be applied to that particular if check (if true) must be indented.

In [29]:
x=.4
if x<0.5:
    print("Heads")
elif x>0.5:
    print("Tails")
else:
    print("Tie")


Heads


#### - While loops
Again, we have the same basic form for the statement (note the colons and indents). Here we use the shorthand notation $x+=1$ for performing the calculation $x = x + 1$:

In [30]:
# Add ones (1) for ten times using while
x=0
while x<10:
    x+=1
    print(x)

1
2
3
4
5
6
7
8
9
10


In [32]:
# now do the same and check if x < 10
x=0 
while x<10:
    x+=1
    print(x<10)

# now print out the x value
print(x)

True
True
True
True
True
True
True
True
True
False
10
